spring:
  datasource:
    #    url: jdbc:mysql://47.95.214.173:3306/copy_meter?serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/copy_meter_system?serverTimezone=GMT%2B8
    username: shuirun
    password: Password
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 10001
logging:
  config:
